# Site settings
title: "My online resume."
description: "My online resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Evan Chime"
resume_title:                   "Software Engineer"
resume_contact_email:           "evan@softgorithm.com"
resume_contact_telephone:       "+44 740363 8832"
resume_contact_address:         "50 Kashgar Road SE18 1HS London UK"
resume_header_contact_info: "50 Kashgar Road SE18 1HS London UK | +44 740363 8832 | evan@softgorithm.com"
resume_header_intro: "<p>Software Engineer with 5+ years experience focused on supporting large-scale software systems. Excellent experience in analysis, design, development, testing, and implementation of various internet-based applications. Expert in a variety of platforms, languages, and embedded systems. Adept at going beyond that of an engineer to that of a user advocate, designer, developer, and tester. Supportive and enthusiastic team player dedicated to streamlining processes and efficiently resolving project issues.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/evanchime"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/evanchime"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://evanchime.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default


# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
